using Microsoft.AspNetCore.Mvc.ModelBinding.Validation;
using System.ComponentModel.DataAnnotations;

namespace Multi_Page_WebApp_Contacts.Models
{
    public class Contact
    {
        // Adding ID/primary key property to be auto generated by EF framework.
        public int ContactId { get; set; }

        [Required(ErrorMessage = "Please enter a name.")]
        [RegularExpression(@"^[a-zA-Z\s]+$", ErrorMessage = "Name can only contain letters and spaces")]
        public string Name { get; set; } = string.Empty;

        [Required(ErrorMessage = "Please enter a phone number (Digits only, ex: 1234567890.")]
        [RegularExpression(@"^\d{10}$", ErrorMessage = "The phone number must be exactly 10 digits long.")]
        public string? PhoneNumber { get; set; }

        [Required(ErrorMessage = "Please enter an address.")]
        public string? Address { get; set; }

        [Required(ErrorMessage = "Please enter a note.")]
        public string? Note { get; set; }
    }
}
